// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO87UMBAhYoyoc18z08C1AmHmIdjrgDug',
    appId: '1:223687931206:web:a201a1104fabae28f7e147',
    messagingSenderId: '223687931206',
    projectId: 'cubesnap-6166d',
    authDomain: 'cubesnap-6166d.firebaseapp.com',
    databaseURL: 'https://cubesnap-6166d-default-rtdb.firebaseio.com',
    storageBucket: 'cubesnap-6166d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh-hTa3-hzfQCsHQkqGD4OtwTyQwSWbBA',
    appId: '1:223687931206:android:28d5a57023666640f7e147',
    messagingSenderId: '223687931206',
    projectId: 'cubesnap-6166d',
    databaseURL: 'https://cubesnap-6166d-default-rtdb.firebaseio.com',
    storageBucket: 'cubesnap-6166d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO87UMBAhYoyoc18z08C1AmHmIdjrgDug',
    appId: '1:223687931206:web:fdfdb422287e00e1f7e147',
    messagingSenderId: '223687931206',
    projectId: 'cubesnap-6166d',
    authDomain: 'cubesnap-6166d.firebaseapp.com',
    databaseURL: 'https://cubesnap-6166d-default-rtdb.firebaseio.com',
    storageBucket: 'cubesnap-6166d.firebasestorage.app',
  );
}
